### ISSUE TITLE
implementar um captcha pra melhor segurança contra ataques de bots

### ISSUE THREAD

**Issue by maizenalegal** [servidorsemnome/gatekeeper#1]
acho que se você fizesse a implementação de um captcha no sistema de autenticação o servidor ficaria mais seguro contra ataques de bots

**Comment by doceazedo** [comment]
Valeu a sugestão, no caso isso teria que ser implementado no **[Kratos](https://github.com/servidorsemnome/kratos-iam-svc)**, ele que cuida da parte de login/senha em si, então se puder reabrir esse issue lá eu agradeço. Inclusive, parece que o Ory Kratos já tem um planejamento pra adicionar medidas como CAPTCHA que seria bom de acompanhar.
